package com.android.kiyori.operitreplica.state

import com.android.kiyori.operitreplica.model.OperitReplicaCharacterOption
import com.android.kiyori.operitreplica.model.OperitReplicaCharacterSortOption
import com.android.kiyori.operitreplica.model.OperitReplicaConversation
import com.android.kiyori.operitreplica.model.OperitReplicaConversationGroup
import com.android.kiyori.operitreplica.model.OperitReplicaConversationSection
import com.android.kiyori.operitreplica.model.OperitReplicaHistoryDisplayMode
import com.android.kiyori.operitreplica.model.OperitReplicaMessage
import com.ai.assistance.operit.ui.features.chat.components.style.input.common.PendingQueueMessageItem

internal data class KiyoriOperitReplicaUiState(
    val currentModelLabel: String = "DeepSeek / Agent",
    val currentMemoryProfileLabel: String = "\u9ED8\u8BA4\u8BB0\u5FC6",
    val availableModelLabels: List<String> = emptyList(),
    val currentCharacterLabel: String = "Operit",
    val activeConversationId: String = "chat-main",
    val selectedCharacterId: String = "operit-agent",
    val historySearchQuery: String = "",
    val inputText: String = "",
    val inputTokenCount: Int = 12,
    val outputTokenCount: Int = 32,
    val currentWindowSize: Int = 1720,
    val contextUsagePercentage: Float = 0f,
    val chatHeaderTransparent: Boolean = false,
    val chatHeaderOverlayMode: Boolean = false,
    val chatHeaderHistoryIconColor: Int? = null,
    val chatHeaderPipIconColor: Int? = null,
    val showHistoryPanel: Boolean = false,
    val showStatsMenu: Boolean = false,
    val showModelSelectorPopup: Boolean = false,
    val showFeaturePanel: Boolean = false,
    val showAttachmentPanel: Boolean = false,
    val showFullscreenEditor: Boolean = false,
    val isInputProcessing: Boolean = false,
    val inputProcessingLabel: String = "",
    val inputProcessingProgress: Float = 0f,
    val pendingQueueMessages: List<PendingQueueMessageItem> = emptyList(),
    val isPendingQueueExpanded: Boolean = true,
    val showCharacterSelector: Boolean = false,
    val showWorkspacePanel: Boolean = false,
    val hasEverOpenedWorkspace: Boolean = false,
    val isWorkspacePreparing: Boolean = false,
    val workspaceReloadVersion: Int = 0,
    val showComputerPanel: Boolean = false,
    val showHistorySearchBox: Boolean = false,
    val showHistorySettingsDialog: Boolean = false,
    val showSwipeHint: Boolean = false,
    val historyDisplayMode: OperitReplicaHistoryDisplayMode = OperitReplicaHistoryDisplayMode.BY_FOLDER,
    val autoSwitchCharacterCard: Boolean = true,
    val autoSwitchChatOnCharacterSelect: Boolean = false,
    val enableThinking: Boolean = true,
    val enableTools: Boolean = true,
    val enableMemory: Boolean = true,
    val enableStream: Boolean = true,
    val enableVoice: Boolean = false,
    val enableWorkspace: Boolean = true,
    val enableNotification: Boolean = false,
    val thinkingQualityLevel: Int = 2,
    val enableMaxContextMode: Boolean = false,
    val baseContextLengthInK: Float = 8f,
    val maxContextLengthInK: Float = 32f,
    val enableMemoryAutoUpdate: Boolean = true,
    val isAutoReadEnabled: Boolean = false,
    val isAutoApproveEnabled: Boolean = false,
    val showModelProvider: Boolean = false,
    val showModelName: Boolean = false,
    val showRoleName: Boolean = false,
    val showMessageTokenStats: Boolean = false,
    val showMessageTimingStats: Boolean = false,
    val disableStreamOutput: Boolean = false,
    val disableUserPreferenceDescription: Boolean = false,
    val disableStatusTags: Boolean = false,
    val characterSortOption: OperitReplicaCharacterSortOption = OperitReplicaCharacterSortOption.DEFAULT,
    val attachments: List<String> = emptyList(),
    val characterOptions: List<OperitReplicaCharacterOption> = emptyList(),
    val conversationGroups: List<OperitReplicaConversationGroup> = emptyList(),
    val conversations: List<OperitReplicaConversation> = emptyList(),
    val conversationMessages: Map<String, List<OperitReplicaMessage>> = emptyMap(),
    val activeConversation: OperitReplicaConversation? = null,
    val activeMessages: List<OperitReplicaMessage> = emptyList(),
    val groupedConversations: List<OperitReplicaConversationSection> = emptyList(),
)
